feat: add Python service build and deploy workflow with ruff for monorepo CI
taxdown/.github pull request #16
Opened 2024-12-14 12:04 UTC by javiermrcom

# [JIRA-ID]

## What changes does this PR introduce

- [X] Feature: add Python service build and deploy workflow with ruff for monorepo CI

## Any background context you want to provide

Cuando se deje de usar el actual "python-service", renombraría este

2024-12-17 17:59 UTC, JoaquinFernandez requested changes

2024-12-17 17:59 UTC, JoaquinFernandez commented on .github/workflows/python-service-ruff.yml
> +        uses: aws-actions/configure-aws-credentials@v1-node16
Actualizar

2024-12-17 17:59 UTC, JoaquinFernandez commented on .github/workflows/python-service-ruff.yml
> +        uses: actions/checkout@v3
Creo que ya hay v4

2024-12-17 17:59 UTC, JoaquinFernandez commented on .github/workflows/python-service-ruff.yml
> +        uses: actions/setup-node@v3
Creo que hay v4

2024-12-17 17:59 UTC, JoaquinFernandez commented on .github/workflows/python-service-ruff.yml
> +        uses: dawidd6/action-download-artifact@v2
no se puede usar el download artifact de github?

2024-12-18 09:35 UTC, javiermrcom commented on .github/workflows/python-service-ruff.yml
> +        uses: dawidd6/action-download-artifact@v2
Lo que se hace aquí es descargar el artefacto de la rama main para posteriormente comparar coverages, esto no lo permite el artifact de github

> actions/download-artifact solo puede descargar artefactos del workflow actual. No puede acceder a artefactos de otros workflows o de la rama main

2024-12-18 10:33 UTC, JoaquinFernandez approved these changes
<img src="https://media0.giphy.com/media/b28VvUmqwada1tyaw2/giphy.gif"/>

2024-12-18 12:09 UTC, merged